---
docs_dir: docs
edit_uri: edit/master/docs
repo_url: https://github.com/rhythmictech/terraform-terraform-template
site_description: Sblack's public knowlegebase
site_name: The 12 Clouds of Christmas Year 10 Demo
# site_url: https://sblack4.github.io

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex
  - smarty
  - toc

plugins:
  - search

theme:
  name: 'material'
  feature:
    tabs: true
  palette:
        primary: 'black'
        accent: 'deep-orange'
